
import Head from 'next/head'
import {useState} from 'react'
import {People as IPeople} from '../typeInterfaces'

//Components
import Navbar from '../components/Navbar'
import InviteList from '../components/InviteList'
import InviteForm from '../components/InviteForm'

export interface IState {
  people :IPeople[]
  setPeople: React.Dispatch<React.SetStateAction<IPeople[]>>
}
export default function Home(){

    const [people, setPeople] = useState<IState["people"]>([])

  return (
    <div className="bg-slate-200 min-h-screen">
      <Head>
        <title>Party Invite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
      <div className="max-w-6xl mx-auto mt-5 flex justify-between">
        <InviteList people={people}/>
        <InviteForm people={people} setPeople={setPeople}/>
      </div>
    </div>
  )
}


